### ISSUE TITLE
Create sdk-vpp chain element for creating loopback interface attached to the fib table 

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-vpp#364]
## Depends on
https://github.com/networkservicemesh/sdk-vpp/issues/341

## Context
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/1

## Description

We need to 
1. create a loopback interface attached to the fib table
2. assign its IP address to the loopback interface.
3.  program a route in the fib table to the SrcIP for the NSC connecting and point out the interface.

**Comment by glazychev-art** [comment]
I would like to show my understanding of `vl3` and `loopback` interface.

Chain ([modification of this](https://github.com/networkservicemesh/cmd-nse-icmp-responder-vpp/blob/main/main.go#L168-L177)):
```
...
point2pointipam.NewServer(ipnet),
iptable.NewServer(),   // - #1
loopback.NewServer(),  // - #2
mechanisms.NewServer(map[string]networkservice.NetworkServiceServer{
	memif.MECHANISM: chain.NewNetworkServiceServer(
		sendfd.NewServer(),
		up.NewServer(ctx, vppConn),
		mtu.NewServer(vppConn),        //
		routes.NewServer(vppConn),     //
		unnumbered.NewServer(vppConn), // - #3
		tag.NewServer(ctx, vppConn),
		memif.NewServer(vppConn),
	),
}),
...
```

**1. iptable**
Creates an ip-table (if doesn't exist) for a given NetworkService.
_Does:_
-Stores tableId in metadata.
-Checks - if  NetworkService usage counter is 0 - deletes ip-table

**2. loopback**
Creates an loopback interface (if doesn't exist) for a given tableID (from iptable metadata).
_Does:_
-Stores loopback swIfIndex in metadata.
-Adds itself to ip-table (from iptable metadata).
-_Assigns IP-address to itself (from `connection.GetContext().GetIpContext()`)_
-Checks - if ip-table usage counter is 0 - deletes loopback interface.

**3.  unnumbered**
New chain element. Sets unnumbered interface.
These elements:
```
		mtu.NewServer(vppConn),       
		routes.NewServer(vppConn),  
		ipaddress.NewServer(vppConn),
```
constitute `connectioncontext` chain element.
I suggest to replace `ipaddress -> unnumbered` in vl3 endpoint.
_Does:_
Sets unnumbered interface (gets loopback swIfIndex and ifindex from metadata).

**Another approach**
I think, it would be better to use `ipaddress` chain in step #2 to set ip-address for the loopback. But we need to change chain element for that, because it uses ifindex.Load(...) [inside](https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/connectioncontext/ipcontext/ipaddress/common.go#L34). For example, add flag like this:
```
...
ipaddress.NewServer(..., isUsedForLoopback)
loopback.NewServer(), 
...
```

**Comment by edwarnicke** [comment]
1. Could we rename  'iptable' to 'vrf' so as not to confuse it with the linux iptables.  Other  than naming you are completely right :)
2. Your loopback sounds right :)
3. unnumbered is also good :)

One 'Additions' I'd suggest simply giving ipaddress.NewServer the Options pattern with an Option like:

```go
func WithLoadSwIfIndex(func(ctx context.Context, isClient bool) (value interface_types.InterfaceIndex, ok bool)) Option {...}
```

Default to using the ifindex.Load function ... but then you can optionall override it with another Load.

One thing to keep in mind though... do we want to keep resetting the IP on the loopback with each new connection (even if its the same value)?

**Comment by edwarnicke** [comment]
Also... how are you getting ipam for the dst IP for the loopback since you only need it once?

**Comment by glazychev-art** [comment]
I don't quite understand. Why do we need to reset IP address with new connection?

**Comment by glazychev-art** [comment]
https://github.com/networkservicemesh/sdk-vpp/issues/364#issuecomment-918213311
That's a good question
